### ISSUE TITLE
hashHistory

### ISSUE THREAD

**Issue by layneanderson** [alpertuna/react-metismenu#13]
Hi,

Love the new features!

I'm using '[hashHistory](https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#hashhistory)' in my **react-router** config (and unfortunately its not easy for me to switch away from).  With '_hashHistory_' it will always append a hash to the end of the URL (for example:  `/menu3?_k=xxmrad`), so the `activeLinkFromLocation` search will always fail.  Any chance you could widen the location match to handle this?

Regards,

Layne

**Comment by layneanderson** [comment]
Hmm, maybe put this on the back burner.  I need to investigate more.  When I hit refresh manually everything works fine, but not when I click a link.

**Comment by alpertuna** [comment]
Hello @layneanderson,

Thanks for the report.
Are you using `react-metismenu-router-link`, and did it happen when you navigate the router with another `Link` of `react-router`?

**Comment by layneanderson** [comment]
Hi @alpertuna,

Yes, I am using react-metismenu-router-link.  This one seems a little weird, which probably means the issue is in my code.  When I start fresh (browser refresh) the menu and active link shows up ok, however, when I click on the same link (or any other) it collapses the menu.  I'm console logging `window.location.hash` and in both cases they are exactly the same except for characters after the `?_k=`.

In explaining this here, I think I know what's wrong.  I'm changing the menu _content_ object based upon my router path, so we're most likely in a race condition.  I need to refactor my code anyways because I need to handle wildcards in my routes, so this problem will go away when I make use of the other active link methods.

Sorry for the diversion and thanks again for creating such a great component.

Regards,

Layne

**Comment by alpertuna** [comment]
Ok, If problem stills or similar cases happen, I'm here, you can reopen issue.
Also thanks for kind words.
Cheers.
