### ISSUE TITLE
No scroll when menu is too long?

### ISSUE THREAD

**Issue by SlowburnAZ** [alpertuna/react-metismenu#15]
Is it possible to have the menu be scrollable when the menu is too long to fit in the page vertically?

**Comment by SlowburnAZ** [comment]
Nevermind...  can probably just do this with CSS

**Comment by alpertuna** [comment]
@SlowburnAZ Yes, `react-metismenu` is rendered as a `display: block` `div` with `standart.css`. And for other placement cases, your application's css is responsible.
