### ISSUE TITLE
react-metismenu with ajax and react-metismenu-router-link causes react warning

### ISSUE THREAD

**Issue by cryptk** [alpertuna/react-metismenu#18]
When using MetisMenu as `<MetisMenu LinkComponent={RouterLink} ajax="/menu.json"/>` the following warning appears in the console a few times:

```Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.```

If I either provide the menu structure without using ajax (just passing in a content prop) or I do it with ajax but without using react-metismenu-router-link, then the warnings go away.

I know it's only a warning and not an error, and everything seems to be working properly otherwise, but I just wanted to make sure that I am not doing something incorrectly.  I'm a bit new to ReactJS so any insight if I am doing something improperly would definitely be appreciated.

Here is the json structure of my menu:

```[
  {
    "icon": "home",
    "label": "Home",
    "to": "/"
  },
  {
    "icon": "dashboard",
    "label": "Monitoring",
    "content": [
      {
        "icon": "exclamation",
        "label": "Events",
        "content": [
          {
            "icon": "list-alt",
            "label": "All Events",
            "to": "/monitoring/events"
          },
          {
            "icon": "list-alt",
            "label": "Dashboard 1",
            "to": "/monitoring/events/dashboard1"
          },
          {
            "icon": "list-alt",
            "label": "Dashboard 2",
            "to": "/monitoring/events/dashboard2"
          },
          {
            "icon": "list-alt",
            "label": "Dashboard 3",
            "to": "/monitoring/events/dashboard3"
          }
        ]
      },
      {
        "icon": "check-square",
        "label": "Checks",
        "to": "/monitoring/checks"
      },
      {
        "icon": "desktop",
        "label": "Clients",
        "to": "/monitoring/clients"
      }
    ]
  },
  {
    "icon": "external-link",
    "label": "Source",
    "externalLink": true,
    "to": "https://github.com/cryptk/opsy-ui"
  }
]
```

**Comment by alpertuna** [comment]
Hi @cryptk,
You are right. There were a problematic part, misplaced action dispatcher.
Now it's fixed with `react-metismenu-router-link@1.0.1`
