### ISSUE TITLE
Customising nth level containers

### ISSUE THREAD

**Issue by ppounder** [alpertuna/react-metismenu#25]
Hi there,

I'm using my own CSS and I'm trying to integrate this into the Metismenu. I can only seem to add styles to all ul's. However I'm looking at adding the following ````nav nav-second-level collapse```` to second level (and third etc) ul's. Its like I could do with a classNameContainerNotVisible (I can't really add this to a classNameContainer - it has to be second level+).

Will I have to do a custom function?

Kind regards,

Paul

**Comment by ppounder** [comment]
Ok found a way if anyone is interested.
I set the Menu classNameContainer's to be all with the collapse in. I then created a setupMenu function to iterate through all the first child ul's and change them to ````nav metismenu````

````
<ReactMenu
    ref="mainmenu"
    classNameContainer="nav metismenu nav-second-level collapse"
    noBuiltInClassNames={true}
    classNameStateIcon="arrow"
    classNameContainerVisible="nav nav-second-level collapse in"
    classNameItemActive="active"
    classNameItemHasActiveChild="active"
    content={content}
    LinkComponent={RouterLink} />
</div>
````

````
setupMenu(){
    //remove nav metismenu nav-second-level collapse off first uls
    let elements = document.querySelectorAll('.navbar-default ul:nth-child(1)');
    for(let i = 0; i < elements.length; i++){
        elements[i].className = "nav metismenu";
    }
}
````

**Comment by alpertuna** [comment]
Hi @ppounder,
Thanks for your idea and solution. I noted it and I may add this nth class name support. It looks it is necessary for easy usage.
