### ISSUE TITLE
Deprecated warning for PropTypes

### ISSUE THREAD

**Issue by isoloviev** [alpertuna/react-metismenu#28]
Hello,

Ive got the following warning:

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Do you have plans to start using prop-types package instead of built-in?

**Comment by alpertuna** [comment]
Hi @isoloviev, yes I will migrate it to `prop-types` package soon.

**Comment by alpertuna** [comment]
Now it should be done by `v1.4.0-alpha.1`
