### ISSUE TITLE
Custom Properties For Each Item In Content

### ISSUE THREAD

**Issue by jmgarciamari** [alpertuna/react-metismenu#30]
I'm trying to add a custom property of type object for each item in content array and when I trigger this.props.activateMe my custom property isn't located in this.props. How Can I access to this property??
Thanks

**Comment by alpertuna** [comment]
Hi @jmgarciamari, only [these](https://github.com/alpertuna/react-metismenu#customizing-link-component) properties are injected.
If you use your own custom link component, you can pass your custom object via `to` key of menu item like this;
```javascript
const content = [
  {
    icon: 'icon-class-name',
    label: 'Label of Item',
    to: { /* your custom object */ },
  },
  //...
];
```
