### ISSUE TITLE
Typescript  d.ts

### ISSUE THREAD

**Issue by UweWindt** [alpertuna/react-metismenu#4]
Do you have a Typescript interface for react-metismenu?

**Comment by alpertuna** [comment]
I don't have for now and I am not experienced in typescript. If you are able to produce an interface, you can open a pull request, and I can help you to improve it and make it suitable for react-metismenu.

**Comment by UweWindt** [comment]
Unfortunately I'm a relative newbie at Typescript. But i will try to write a d.ts file. Give me some time.

**Comment by alpertuna** [comment]
:+1: Ok, time is no problem :blush:

**Comment by alpertuna** [comment]
Currently there is no typescript support, in future it may be on more demand.

**Comment by profaddy** [comment]
please add typescript support
