### ISSUE TITLE
Visibility breaks when 'content' is dynamically generated

### ISSUE THREAD

**Issue by layneanderson** [alpertuna/react-metismenu#6]
I dynamically create my menu content object.  

If I have a lower down menu item expanded (say menu 4 in dev example) and I then change my _content_ item to one that doesn't have the lower menu item (menu 4) it still acts like it is open.  Clicking on the new menu throws an error (_Cannot read property 'closeContainer' of null_). 

Bit hard to explain but hopefully it can be understood.  I might take a crack at fixing this myself if I get some time.

**Comment by alpertuna** [comment]
Ok, I got the problem.
I followed your instructions, and found the problem. It's happened when you decrease the number of sub items. The reason of that is about handling item references with anonymous function and I didn't realize that react sends again refs of deleted items as null to tell these are deleted, and container gets it as an item.
I solved it and will push presently.

**Comment by alpertuna** [comment]
@layneanderson 
Could you like to pull f50d373 and try it again?

**Comment by layneanderson** [comment]
Yes, works great.  Thanks!
