### ISSUE TITLE
Server rendering support

### ISSUE THREAD

**Issue by garbin** [alpertuna/react-metismenu#7]
It seems like server rendering not support yet. do you have plan to support it?

**Comment by garbin** [comment]
import 'react-metismenu' rasied an error on server

```
/work/koapp/node_modules/react-metismenu/dist/react-metismenu.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof export
s&&"object"==typeof module?module.exports=t(require("react")):"function"==typeof define&&define.amd?
define(["react"],t):"object"==typeof exports?exports.ReactMetismenu=t(require("react")):e.ReactMetis
menu=t(e.React)}(this,function(e){return function(e){function t(i){if(n[i])return n[i].exports;var o
=n[i]={exports:{},id:i,loaded:!1};return e[i].call(o.exports,o,o.exports,t),o.loaded=!0,o.exports}va
r n={};return t.m=e,t.c=n,t.p="",t(0)}([function(e,t,n){"use strict";function i(e){return e&&e.__esM
odule?e:{"default":e}}Object.defineProperty(t,"__esModule",{value:!0});var o=n(2),r=i(o);n(7),t["def
ault"]=r["default"]},,function(e,t,n){"use strict";function i(e){return e&&e.__esModule?e:{"default"
:e}}Object.defineProperty(t,"__esModule",{value:!0});var o=n(3),r=i(o),s=n(4),a=i(s),u=n(6),l=i(u),c
=function(e){return r["default"].createElement("div

TypeError: Cannot read property 'userAgent' of undefined
    at /work/koapp/node_modules/react-metismenu/dist/react-metismenu.min.js:1:11608
    at /work/koapp/node_modules/react-metismenu/dist/react-metismenu.min.js:1:11524
```

**Comment by alpertuna** [comment]
@garbin
`react-metismenu` bundle has something special for browser, for example embedded styles. That's why it tries to reach browser environments. This can be solved by ommiting browser things.

I'm not experienced server side rendering so much, so I wonder how does your server work. Server does full page static render and client does nothing, or you use react for both side, server and client?

**Comment by garbin** [comment]
server side only does the initial rendering only. I use react for both side on my universal app. What about putting styles into a separate files? like https://github.com/JedWatson/react-select does?

**Comment by alpertuna** [comment]
I got the point. Actually at first, style was seperated but I embedded it to be convenient. Nonetheless I can seperate back if it causes cases like this.
Ok, I will do it and publish today.

**Comment by garbin** [comment]
Thank you for your great job!

**Comment by alpertuna** [comment]
@garbin Can you try react-metismenu@v0.5.0 ?
By the way css files is under `dist/` folder and you need to include manually.

**Comment by garbin** [comment]
@alpertuna Yes,I'm glad to! I will test it tomorrow morning. Now it's 00:10 in my city:) I will give you feedback ASAP

**Comment by alpertuna** [comment]
Ok, It is not problem :blush:

**Comment by garbin** [comment]
Yes, the error is gone.👍  closed.
