### ISSUE TITLE
How can I set/change the className of wrapper, container, item?

### ISSUE THREAD

**Issue by garbin** [alpertuna/react-metismenu#8]
I can't find any info in docs about how to set active className on menu item when it being clicked.
I checkout the code, the Wrapper, Container, Item's className is hard code, it can't be change now. I think wrapper, container, menu item should be able to custom their className to easy fits any css framework or their own styles.

**Comment by alpertuna** [comment]
In my projects I uses its own classname and overwrites with custom css. However, you are right. People should be able to put different classnames. I also commit a patch for that

**Comment by alpertuna** [comment]
Hello @garbin 
Now, you are able to customize styles with v0.6.0 minor update.
These readme sections may help you;
- [Properties](https://github.com/alpertuna/react-metismenu#properties)
- [Customizing Styles](https://github.com/alpertuna/react-metismenu#customizing-styles)

Feel free to open new issues :blush:

**Comment by garbin** [comment]
Wow! So  efficient! I'll give it a try then give you feedback ASAP.
