### ISSUE TITLE
How to set className of selected(or opened) menu item

### ISSUE THREAD

**Issue by garbin** [alpertuna/react-metismenu#9]
In my project, I'm using this library for admin sidebar menu, so I should show user which item he clicked(opened). 

fortunately, the theme what I'm using has a online demo, If my describe is difficult to understand. you can checkout it http://modularcode.io/modular-admin-html/ . I think you'll get the point easily

**Comment by alpertuna** [comment]
Shortly, you said, higlighting active menu. I am already working on this :+1:

**Comment by alpertuna** [comment]
Soon, I will publish a major version which written from scratch. Because current structure is simple and can't afford complicated controls like automatically pre-opened sub menus which consists active link when page is loaded. Or externally manuel activating a menu via ref methods for Single Page Applications.

**Comment by alpertuna** [comment]
Hello @garbin 
Now `v1.0.0-alpha.1` is available and you are able to control active links and customizing styles of course.
Here README parts may help you;
- [Properties](https://github.com/alpertuna/react-metismenu#metismenu-react-component-properties)
- [Active Link Selectors](https://github.com/alpertuna/react-metismenu#metismenu-react-component-properties)
- [Using Your Own Class Names](https://github.com/alpertuna/react-metismenu#using-your-own-class-names) (Added `classNameLinkActive` prop)
- [Demo Page](https://alpertuna.github.io/react-metismenu/)

I will be waiting for your feedback after trying latest release :blush:

**Comment by garbin** [comment]
@alpertuna Wow! Great job! I will give you feedback ASAP.
